import type { Tool } from "@/app/lib/types";

// Ratings are 1–5. Matrix columns are derived per category from these keys.
export const SEED_TOOLS: Tool[] = [
  // ───────────────── AI MODELS ─────────────────
  {
    id: "claude-fable-51",
    name: "Claude Fable 5.1",
    creator: "Anthropic",
    category: "AI Models",
    tagline: "Anthropic's flagship — built for long-running agents, coding, and research.",
    strengths: [
      "Best-in-class reasoning & long-running agentic tasks",
      "Excellent, careful coding",
      "Very long context window with cheap cache reads",
      "Strong on documents, spreadsheets, and slides",
    ],
    weaknesses: [
      "Premium price vs lighter models",
      "Has a knowledge cutoff (use tools for live data)",
      "Overkill for simple, single-turn tasks",
    ],
    use_cases: [
      "Hardest reasoning & planning",
      "Complex multi-file coding",
      "Building autonomous, long-running agents",
      "Deep research & document work",
    ],
    pricing: "Premium flagship tier — $10/$50 per MTok, cached reads ~$0.25/MTok",
    when_to_use: "When you need the top capability ceiling for hard reasoning, coding, or agents.",
    ratings: { Reasoning: 5, Speed: 3, Context: 5, Coding: 5, "Web Access": 3, Value: 4 },
  },
  {
    id: "claude-opus-55",
    name: "Claude Opus 5.5",
    creator: "Anthropic",
    category: "AI Models",
    tagline: "Anthropic's newest model — matches Fable on most work, cheaper to run.",
    strengths: [
      "State-of-the-art coding & knowledge work",
      "1M-token context window",
      "Costs ~40% less than Opus 5 on typical workloads",
      "Strong instruction-following",
    ],
    weaknesses: [
      "Still a premium-tier price vs Sonnet/Haiku",
      "Has a knowledge cutoff (use tools for live data)",
    ],
    use_cases: [
      "Hardest reasoning & planning",
      "Complex multi-file coding",
      "Building autonomous agents",
      "Deep research & analysis",
    ],
    pricing: "Premium tier, cheaper than Opus 5 (check Anthropic for current rates)",
    when_to_use: "When you want near-Fable capability at a lower cost.",
    ratings: { Reasoning: 5, Speed: 4, Context: 5, Coding: 5, "Web Access": 3, Value: 5 },
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    creator: "Anthropic",
    category: "AI Models",
    tagline: "The workhorse — near-flagship quality at much higher speed/value.",
    strengths: [
      "Best speed-to-intelligence balance",
      "Excellent coding & tool use",
      "Long context window",
      "Great default for most apps & agents",
    ],
    weaknesses: [
      "A notch below Fable/Opus on the very hardest tasks",
      "Has a knowledge cutoff",
    ],
    use_cases: [
      "Most production apps & agents",
      "Day-to-day coding",
      "High-volume automation",
    ],
    pricing: "Mid-tier — strong value ($2/$10 per MTok, check Anthropic for current rates)",
    when_to_use: "Your default — when you want quality and speed without top-tier cost.",
    ratings: { Reasoning: 5, Speed: 5, Context: 5, Coding: 5, "Web Access": 3, Value: 5 },
  },
  {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    creator: "OpenAI",
    category: "AI Models",
    tagline: "OpenAI's flagship — state-of-the-art on computer use, coding, and browsing.",
    strengths: [
      "State-of-the-art computer use, browsing & software engineering",
      "1.1M-token context window",
      "Async tool calls & mid-turn steering for long workflows",
      "Largest developer ecosystem & tooling",
    ],
    weaknesses: [
      "Premium pricing at the top tier",
      "Highest cybersecurity capability tier means tighter usage guardrails",
    ],
    use_cases: [
      "General-purpose AI products",
      "Agentic computer-use & browsing tasks",
      "Consumer-facing apps",
    ],
    pricing: "Premium flagship tier — $10/M input, $1/M cached input, $50/M output",
    when_to_use: "When you want a capable all-rounder with the biggest ecosystem and strong computer-use.",
    ratings: { Reasoning: 5, Speed: 4, Context: 5, Coding: 5, "Web Access": 5, Value: 4 },
  },
  {
    id: "gemini-31-pro",
    name: "Gemini 3.1 Pro",
    creator: "Google DeepMind",
    category: "AI Models",
    tagline: "Massive context + best-in-class multimodal, great price-performance.",
    strengths: [
      "Huge (1M+) context window",
      "Excellent image / video / multimodal",
      "Very competitive pricing",
      "Deep Google Workspace integration",
    ],
    weaknesses: [
      "Coding slightly behind Claude/GPT flagships",
      "Occasional inconsistency on complex reasoning",
    ],
    use_cases: [
      "Huge-document / long-context tasks",
      "Image & video understanding",
      "Budget-conscious scale",
    ],
    pricing: "Competitive — cheap Flash tier, paid Pro tier",
    when_to_use: "When you need massive context or multimodal at great value.",
    ratings: { Reasoning: 5, Speed: 4, Context: 5, Coding: 4, "Web Access": 5, Value: 5 },
  },
  {
    id: "grok-47",
    name: "Grok 4.7",
    creator: "xAI",
    category: "AI Models",
    tagline: "Real-time model wired into X — strongest on live, current events.",
    strengths: [
      "Real-time access to X / live data",
      "Strong on current events & trends",
      "Longer, more careful reasoning on hard coding tasks",
      "Fast iteration cadence",
    ],
    weaknesses: [
      "Smaller ecosystem and tooling",
      "Less proven on complex coding vs Claude/GPT flagships",
      "Tied closely to the X platform",
    ],
    use_cases: [
      "Real-time social / news context",
      "Trend monitoring",
      "Longer-running coding tasks",
    ],
    pricing: "Included with X Premium+ · API ~$2/M input, $6/M output",
    when_to_use: "When you want live X/Twitter context and current-events awareness.",
    ratings: { Reasoning: 4, Speed: 4, Context: 4, Coding: 4, "Web Access": 5, Value: 3 },
  },

  // ───────────────── CODING AGENTS ─────────────────
  {
    id: "claude-code",
    name: "Claude Code",
    creator: "Anthropic",
    category: "Coding Agents",
    tagline: "Agentic coding in your terminal/IDE — reads, writes, runs, and explains.",
    strengths: [
      "Integrated with Claude's reasoning",
      "Can execute code locally",
      "Excellent code explanations",
      "Great for learning and refactoring",
    ],
    weaknesses: [
      "Newer than Cursor",
      "Fewer built-in IDE features",
      "Requires terminal comfort",
    ],
    use_cases: [
      "Building projects from scratch",
      "Code review and refactoring",
      "Understanding existing code",
      "Rapid prototyping",
    ],
    pricing: "Included with Claude subscription / API usage",
    when_to_use: "When learning, understanding code, or building end to end with reasoning.",
    ratings: { "IDE Experience": 3, "Learning Focus": 5, Professional: 4, Autonomy: 5, "Ease of Use": 4, Value: 5 },
  },
  {
    id: "cursor",
    name: "Cursor",
    creator: "Anysphere",
    category: "Coding Agents",
    tagline: "AI-native VS Code for professional, whole-project development.",
    strengths: [
      "Full IDE features",
      "Can use Claude or GPT",
      "Strong project-wide context",
      "Large, active community",
    ],
    weaknesses: [
      "Paid subscription for full power",
      "Learning curve vs plain editors",
      "Depends on third-party models",
    ],
    use_cases: [
      "Professional development",
      "Full-stack projects",
      "Large codebases",
      "Teams adopting AI coding",
    ],
    pricing: "Free tier · Pro $20/mo",
    when_to_use: "When building real projects professionally in a full IDE.",
    ratings: { "IDE Experience": 5, "Learning Focus": 3, Professional: 5, Autonomy: 4, "Ease of Use": 4, Value: 4 },
  },
  {
    id: "codex",
    name: "Codex",
    creator: "OpenAI",
    category: "Coding Agents",
    tagline: "Code model via API — the engine behind many completion tools.",
    strengths: [
      "Powers many coding platforms",
      "Fast responses",
      "Widely integrated",
      "Reliable for production",
    ],
    weaknesses: [
      "No standalone IDE",
      "Requires API integration",
      "Less deep reasoning on hard problems",
    ],
    use_cases: [
      "Adding coding AI to apps",
      "Code completion tools",
      "Automated code generation",
    ],
    pricing: "Based on OpenAI token pricing",
    when_to_use: "When building code-AI features into your own application.",
    ratings: { "IDE Experience": 2, "Learning Focus": 2, Professional: 4, Autonomy: 3, "Ease of Use": 3, Value: 4 },
  },
  {
    id: "vscode",
    name: "VS Code",
    creator: "Microsoft",
    category: "Coding Agents",
    tagline: "The universal editor — no AI built in, but add any AI via extensions.",
    strengths: [
      "Free & open-source",
      "Massive extension ecosystem",
      "Runs everywhere, lightweight",
      "The base most AI editors are forked from",
    ],
    weaknesses: [
      "No AI on its own (needs extensions)",
      "You assemble your own setup",
    ],
    use_cases: [
      "General development",
      "Maximum control over tooling",
      "Add Copilot / Claude / Codeium",
    ],
    pricing: "Free",
    when_to_use: "When you want a free, universal base and pick your own AI add-ons.",
    ratings: { "IDE Experience": 5, "Learning Focus": 3, Professional: 5, Autonomy: 1, "Ease of Use": 4, Value: 5 },
  },
  {
    id: "windsurf",
    name: "Windsurf",
    creator: "Codeium",
    category: "Coding Agents",
    tagline: "AI-first editor with 'Cascade' — an agent that acts, not just suggests.",
    strengths: [
      "Agentic 'Cascade' flow (runs commands, fixes errors)",
      "Built on VS Code — extensions still work",
      "More autonomous than Cursor",
      "Generous free tier",
    ],
    weaknesses: [
      "Full power needs a paid plan",
      "Newer, smaller community than Cursor",
    ],
    use_cases: [
      "Agentic, hands-off coding",
      "Solo devs who want AI to 'handle it'",
      "Full-stack work",
    ],
    pricing: "Free tier · paid plans for more",
    when_to_use: "When you want an autonomous agent inside a full editor.",
    ratings: { "IDE Experience": 5, "Learning Focus": 3, Professional: 5, Autonomy: 5, "Ease of Use": 4, Value: 4 },
  },
  {
    id: "antigravity",
    name: "Antigravity",
    creator: "Google",
    category: "Coding Agents",
    tagline: "Google's agentic IDE built around autonomous agents, powered by Gemini.",
    strengths: [
      "Agent-first development platform",
      "Powered by Gemini 3",
      "Built on VS Code base",
      "Free during preview",
    ],
    weaknesses: [
      "Very new — still maturing",
      "Tied to Google's AI ecosystem",
      "Smaller community so far",
    ],
    use_cases: [
      "Agent-driven, autonomous coding",
      "Gemini-centric workflows",
      "Exploring the newest agentic IDE",
    ],
    pricing: "Free in preview",
    when_to_use: "When you want Google's agent-first IDE and Gemini-powered autonomy.",
    ratings: { "IDE Experience": 5, "Learning Focus": 3, Professional: 4, Autonomy: 5, "Ease of Use": 4, Value: 4 },
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    creator: "GitHub / OpenAI",
    category: "Coding Agents",
    tagline: "The OG AI coding assistant — best-in-class tab completion, any IDE.",
    strengths: [
      "Excellent autocomplete",
      "Works in VS Code, JetBrains, Neovim",
      "Now has chat + agent modes",
      "No editor switch needed",
    ],
    weaknesses: [
      "Paid subscription",
      "Less autonomous than Cursor/Windsurf",
    ],
    use_cases: [
      "Staying in your current IDE",
      "JetBrains / enterprise teams",
      "Fast inline completions",
    ],
    pricing: "~$10–19/mo (free for some students/OSS)",
    when_to_use: "When you want AI in your existing editor without switching.",
    ratings: { "IDE Experience": 4, "Learning Focus": 3, Professional: 5, Autonomy: 3, "Ease of Use": 5, Value: 4 },
  },

  // ───────────────── AGENT PLATFORMS ─────────────────
  {
    id: "hermes",
    name: "Hermes",
    creator: "Community / open ecosystem",
    category: "Agent Platforms",
    tagline: "Lightweight framework for building task-running autonomous agents.",
    strengths: [
      "Flexible agent orchestration",
      "Tool/function integration",
      "Good for custom autonomous flows",
    ],
    weaknesses: [
      "Requires engineering setup",
      "Smaller community",
      "Less turnkey than hosted platforms",
    ],
    use_cases: [
      "Custom autonomous agents",
      "Multi-step task automation",
      "Tool-augmented workflows",
    ],
    pricing: "Open-source / self-hosted",
    when_to_use: "When you want code-level control over agent behavior.",
    ratings: { Autonomy: 4, Flexibility: 5, "Ease of Use": 3, "Tool Support": 4, Maturity: 3, Value: 4 },
  },
  {
    id: "openhands",
    name: "OpenHands",
    creator: "All Hands AI (open-source)",
    category: "Agent Platforms",
    tagline: "Open-source autonomous software-engineering agent (formerly OpenDevin).",
    strengths: [
      "Autonomous coding tasks",
      "Active open-source community",
      "Runs in a sandboxed environment",
      "Model-agnostic",
    ],
    weaknesses: [
      "Setup complexity",
      "Variable reliability on hard tasks",
      "Resource-heavy",
    ],
    use_cases: [
      "Autonomous bug fixing",
      "Repo-level coding tasks",
      "Agent research and experimentation",
    ],
    pricing: "Open-source / self-hosted (pay model API costs)",
    when_to_use: "When you want an open, autonomous SWE agent you control.",
    ratings: { Autonomy: 5, Flexibility: 4, "Ease of Use": 3, "Tool Support": 4, Maturity: 3, Value: 4 },
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    creator: "Open ecosystem",
    category: "Agent Platforms",
    tagline: "Open agent platform for chaining tools into autonomous workflows.",
    strengths: [
      "Composable tool chaining",
      "Open and extensible",
      "Good for experimentation",
    ],
    weaknesses: [
      "Early-stage maturity",
      "Sparse documentation",
      "Hands-on setup required",
    ],
    use_cases: [
      "Prototyping agent workflows",
      "Tool-chaining experiments",
      "Custom automation agents",
    ],
    pricing: "Open-source / self-hosted",
    when_to_use: "When experimenting with composable, open agent tooling.",
    ratings: { Autonomy: 4, Flexibility: 5, "Ease of Use": 2, "Tool Support": 3, Maturity: 2, Value: 4 },
  },

  // ───────────────── AUTOMATION PLATFORMS ─────────────────
  {
    id: "n8n",
    name: "n8n",
    creator: "n8n GmbH",
    category: "Automation Platforms",
    tagline: "Open-source, self-hostable automation with a mature native AI Agent node.",
    strengths: [
      "Self-hostable and open-source",
      "AI Agent node with ReAct reasoning mode and native MCP support",
      "Handles complex workflows",
      "Code steps when you need them",
    ],
    weaknesses: [
      "Steeper learning curve",
      "Fewer native apps than Zapier",
      "Self-hosting needs maintenance",
    ],
    use_cases: [
      "Complex custom workflows",
      "Self-hosted automation",
      "API-heavy integrations",
    ],
    pricing: "Free (self-hosted) · Cloud tiers available",
    when_to_use: "When you want control and complex, low-cost workflows.",
    ratings: { Power: 5, "Ease of Use": 3, "App Count": 3, "Self-Host": 5, Pricing: 5, Value: 5 },
  },
  {
    id: "make",
    name: "Make (Integromat)",
    creator: "Celonis",
    category: "Automation Platforms",
    tagline: "Visual scenario builder, now with \"Maia\" building scenarios from plain English.",
    strengths: [
      "Powerful visual builder",
      "Maia AI assistant builds scenarios from natural language",
      "1000+ app integrations",
      "Good price-to-power ratio",
    ],
    weaknesses: [
      "Not self-hostable",
      "Steeper than Zapier for beginners",
      "Operations-based pricing can add up",
    ],
    use_cases: [
      "Mid-complexity automations",
      "Multi-step app integrations",
      "Visual workflow design",
    ],
    pricing: "Free tier · Paid plans by operations",
    when_to_use: "When you want a balance of power and ease without self-hosting.",
    ratings: { Power: 4, "Ease of Use": 4, "App Count": 4, "Self-Host": 1, Pricing: 4, Value: 4 },
  },
  {
    id: "zapier",
    name: "Zapier",
    creator: "Zapier Inc.",
    category: "Automation Platforms",
    tagline: "The most beginner-friendly no-code automation, now with autonomous Zapier Agents.",
    strengths: [
      "Easiest to learn",
      "Zapier Agents run tasks autonomously, not just chat",
      "7000+ app integrations",
      "Fast setup",
    ],
    weaknesses: [
      "Limited for complex logic",
      "Gets expensive at scale",
      "Not self-hostable",
    ],
    use_cases: [
      "Simple two-app automations",
      "Quick setup with popular apps",
      "Non-technical users",
    ],
    pricing: "Free tier · Paid plans by tasks",
    when_to_use: "When you want the quickest setup with the widest app coverage.",
    ratings: { Power: 2, "Ease of Use": 5, "App Count": 5, "Self-Host": 1, Pricing: 3, Value: 3 },
  },
];

// Matrix rating columns per category (order matters for the table).
export const MATRIX_COLUMNS: Record<string, string[]> = {
  "AI Models": ["Reasoning", "Speed", "Context", "Coding", "Web Access", "Value"],
  "Coding Agents": ["IDE Experience", "Learning Focus", "Professional", "Autonomy", "Ease of Use", "Value"],
  "Agent Platforms": ["Autonomy", "Flexibility", "Ease of Use", "Tool Support", "Maturity", "Value"],
  "Automation Platforms": ["Power", "Ease of Use", "App Count", "Self-Host", "Pricing", "Value"],
};
